services:
  db:
    container_name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: ggranados
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - dbs:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - dbs
    restart: unless-stopped
  ggranados-api:
    container_name: ggranados-api
    image: galessandro/ggranados-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - dbs
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc.postgresql://db:5432/customer
networks:
  dbs:
    driver: bridge

volumes:
  dbs:
